@startuml
hide empty description

[*] --> S_IDLE : リセット || !uart_enable

S_IDLE :idle状態
S_SEND_START : スタートビットを送信する
S_SEND_DATA : データビットを送信する
S_SEND_PARITY : パリティビットを送信する
S_SEND_STOP : ストップビットを送信する
S_SEND_BREAK :ブレーク送信




S_IDLE --> S_SEND_BREAK : break_send && tx_fifo_empty && (!i_uart_ctsn && hwflow_en)
S_IDLE --> S_SEND_START : !tx_fifo_empty && (!i_uart_ctsn && hwflow_en)
S_SEND_START --> S_SEND_DATA : スタートビットの送信が完了
S_SEND_DATA --> S_SEND_DATA : データビットの送信が完了 && すべてのデータビットを送信していない
S_SEND_DATA --> S_SEND_PARITY : データビットの送信が完了 && すべてのデータビットを送信した && parity != "NONE"
S_SEND_DATA --> S_SEND_STOP : データビットの送信が完了 && すべてのデータビットを送信した && parity == "NONE"
S_SEND_PARITY --> S_SEND_STOP : パリティビットの送信が完了
S_SEND_STOP --> S_IDLE : ストップビットの送信が完了
S_SEND_BREAK --> S_IDLE : break送信が完了


@enduml